services:
  frontend:
    build: frontend
    ports:
      - '5173:5173'
    networks:
      - network
    depends_on:
      backend:
        condition: service_healthy
    volumes:
      - ./frontend/src:/app/src

  backend:
    build: backend
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - PEPPER=XYZ
      - JWT_SECRET=42j892k95kdkasdl312lelasefom3rk30r
      - MAIL_USERNAME=TYPE_HERE_YOUR_EMAIL
      - MAIL_PASSWORD=TYPE_HERE_YOUR_PASSWORD
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - DATASOURCE_URL=jdbc:postgresql://db:5432/hcm-app
      - CORS_ALLOWED_ORIGINS=http://localhost:5173,https://localhost:5173
    ports:
      - 8080:8080
    networks:
      - network
    healthcheck:
      test: wget -qO- http://localhost:8080/actuator/health | grep '"status":"UP"' || exit 1
      interval: 10s
      timeout: 2s
      retries: 10
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=hcm-app
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - network
    healthcheck:
      test: pg_isready -U postgres
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  network:
    driver: bridge

volumes:
  db:
    driver: local