spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hcm-app
    username: postgres
    password: postgres
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
  devtools:
    restart:
      enabled: true
pepper:
  value: XYZ