spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hcm-app
    username: postgres
    password: postgres
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
  devtools:
    restart:
      enabled: true

app:
  jwt:
    secret: 42j892k95kdkasdl312lelasefom3rk30r
    access-expiration: 300000
    refresh-expiration: 3600000
  cors:
    allowed-origins: http://localhost:5173,https://localhost:5173
  pepper:
    value: XYZ

email:
  sender:
    enabled: false

seeders:
  enabled: true