spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hcm-app
    username: postgres
    password: postgres
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
  devtools:
    restart:
      enabled: true

app:
  jwt:
    secret: 42j892k95kdkasdl312lelasefom3rk30r
    access-expiration: 300000
    refresh-expiration: 3600000
  pepper:
    value: XYZ